### ISSUE TITLE
Dans le thème par défaut, implémenter une barre de recherche qui cherche dans les fichiers du dépôt

### ISSUE THREAD

**Issue by DavidBruant** [daktary-team/coup-de-pinceau#1]
Entre autres choses, permet de poser les ressources sans avoir à les trier dans des dossiers tout en ne perdant pas de temps à les chercher

**Comment by DavidBruant** [comment]
Une idée à peut-être implémenter : faire la requête [en mode anonyme depuis le client (10 requêtes par minute)](https://developer.github.com/v3/search/#rate-limit), puis via le [serveur d'API/file-moi-les-clefs (avec l'astuce `client_id` + `client_secret`, 30 req/minutes)](https://developer.github.com/v3/search/#rate-limit)

**Comment by pointbar** [comment]
https://github.com/daktary-team/maquillage/projects/1#card-12302780
